version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/function"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/http"
    schedule:
      interval: "daily"
